version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: embedding-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: embeddings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  embedding-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/embeddings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "app.main"]

volumes:
  postgres_data: